//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crosire.Controlcenter.Setup.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localized {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localized() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Crosire.Controlcenter.Setup.Resources.Localized", typeof(Localized).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string button_back {
            get {
                return ResourceManager.GetString("button_back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        internal static string button_browse {
            get {
                return ResourceManager.GetString("button_browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string button_cancel {
            get {
                return ResourceManager.GetString("button_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        internal static string button_finish {
            get {
                return ResourceManager.GetString("button_finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fresh.
        /// </summary>
        internal static string button_fresh {
            get {
                return ResourceManager.GetString("button_fresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string button_next {
            get {
                return ResourceManager.GetString("button_next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I want to use an already existing MySQL server.
        /// </summary>
        internal static string button_own {
            get {
                return ResourceManager.GetString("button_own", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reconfigurate.
        /// </summary>
        internal static string button_reconfigurate {
            get {
                return ResourceManager.GetString("button_reconfigurate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string button_update {
            get {
                return ResourceManager.GetString("button_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Options.
        /// </summary>
        internal static string group_database {
            get {
                return ResourceManager.GetString("group_database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation Options.
        /// </summary>
        internal static string group_options {
            get {
                return ResourceManager.GetString("group_options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host.
        /// </summary>
        internal static string host {
            get {
                return ResourceManager.GetString("host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your language:.
        /// </summary>
        internal static string sentence_chooselanguage {
            get {
                return ResourceManager.GetString("sentence_chooselanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a list of databases you wish to update below. You can use commas to seperate them:.
        /// </summary>
        internal static string sentence_enterdatabase {
            get {
                return ResourceManager.GetString("sentence_enterdatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your MySQL credentials below. If you don&apos;t have a MySQL server already installed you can leave it at defaults:.
        /// </summary>
        internal static string sentence_entermysql {
            get {
                return ResourceManager.GetString("sentence_entermysql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the full path to your ArmA installation:.
        /// </summary>
        internal static string sentence_enterpath {
            get {
                return ResourceManager.GetString("sentence_enterpath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install required beta patch.
        /// </summary>
        internal static string sentence_installpatch {
            get {
                return ResourceManager.GetString("sentence_installpatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install required redistributables.
        /// </summary>
        internal static string sentence_installredis {
            get {
                return ResourceManager.GetString("sentence_installredis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the server setup!.
        /// </summary>
        internal static string step_1 {
            get {
                return ResourceManager.GetString("step_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your options.
        /// </summary>
        internal static string step_2 {
            get {
                return ResourceManager.GetString("step_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress.
        /// </summary>
        internal static string step_3 {
            get {
                return ResourceManager.GetString("step_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string user {
            get {
                return ResourceManager.GetString("user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controlcenter Version:.
        /// </summary>
        internal static string version {
            get {
                return ResourceManager.GetString("version", resourceCulture);
            }
        }
    }
}
