//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crosire.Controlcenter.Resources {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localized {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localized() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Crosire.Controlcenter.Resources.Localized", typeof(Localized).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Backpack.
        /// </summary>
        internal static string backpack {
            get {
                return ResourceManager.GetString("backpack", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Path to Backup folder.
        /// </summary>
        internal static string backupfolder {
            get {
                return ResourceManager.GetString("backupfolder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Required Build.
        /// </summary>
        internal static string build {
            get {
                return ResourceManager.GetString("build", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add new database.
        /// </summary>
        internal static string button_add_database {
            get {
                return ResourceManager.GetString("button_add_database", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add new player.
        /// </summary>
        internal static string button_add_player {
            get {
                return ResourceManager.GetString("button_add_player", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Start Autobackup.
        /// </summary>
        internal static string button_autobackup_start {
            get {
                return ResourceManager.GetString("button_autobackup_start", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Stop Autobackup.
        /// </summary>
        internal static string button_autobackup_stop {
            get {
                return ResourceManager.GetString("button_autobackup_stop", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Backup Database.
        /// </summary>
        internal static string button_backup {
            get {
                return ResourceManager.GetString("button_backup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        internal static string button_browse {
            get {
                return ResourceManager.GetString("button_browse", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string button_cancel {
            get {
                return ResourceManager.GetString("button_cancel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string button_clear {
            get {
                return ResourceManager.GetString("button_clear", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string button_details {
            get {
                return ResourceManager.GetString("button_details", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string button_exit {
            get {
                return ResourceManager.GetString("button_exit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Generate vehicles.
        /// </summary>
        internal static string button_generate {
            get {
                return ResourceManager.GetString("button_generate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Show Log.
        /// </summary>
        internal static string button_log {
            get {
                return ResourceManager.GetString("button_log", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 1. Configuration.
        /// </summary>
        internal static string button_menu1 {
            get {
                return ResourceManager.GetString("button_menu1", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 2. Administration.
        /// </summary>
        internal static string button_menu2 {
            get {
                return ResourceManager.GetString("button_menu2", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 3. Database.
        /// </summary>
        internal static string button_menu3 {
            get {
                return ResourceManager.GetString("button_menu3", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 4. Information.
        /// </summary>
        internal static string button_menu4 {
            get {
                return ResourceManager.GetString("button_menu4", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Start Realtime Log Monitoring.
        /// </summary>
        internal static string button_monitor_start {
            get {
                return ResourceManager.GetString("button_monitor_start", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Stop Log Monitoring.
        /// </summary>
        internal static string button_monitor_stop {
            get {
                return ResourceManager.GetString("button_monitor_stop", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Change MySQL Password.
        /// </summary>
        internal static string button_mysql_password {
            get {
                return ResourceManager.GetString("button_mysql_password", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string button_ok {
            get {
                return ResourceManager.GetString("button_ok", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Randomize passwords.
        /// </summary>
        internal static string button_random {
            get {
                return ResourceManager.GetString("button_random", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Reload.
        /// </summary>
        internal static string button_reload {
            get {
                return ResourceManager.GetString("button_reload", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Reset Database.
        /// </summary>
        internal static string button_reset {
            get {
                return ResourceManager.GetString("button_reset", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Restore Database.
        /// </summary>
        internal static string button_restore {
            get {
                return ResourceManager.GetString("button_restore", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string button_save {
            get {
                return ResourceManager.GetString("button_save", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Save configuration.
        /// </summary>
        internal static string button_save_config {
            get {
                return ResourceManager.GetString("button_save_config", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Save player.
        /// </summary>
        internal static string button_save_player {
            get {
                return ResourceManager.GetString("button_save_player", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Bytes.
        /// </summary>
        internal static string bytes {
            get {
                return ResourceManager.GetString("bytes", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to B/s.
        /// </summary>
        internal static string bytespersecond {
            get {
                return ResourceManager.GetString("bytespersecond", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Only Daytime.
        /// </summary>
        internal static string check_daytime {
            get {
                return ResourceManager.GetString("check_daytime", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Kick Duplicate.
        /// </summary>
        internal static string check_duplicate {
            get {
                return ResourceManager.GetString("check_duplicate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        internal static string check_enabled {
            get {
                return ResourceManager.GetString("check_enabled", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Persistent Battlefield.
        /// </summary>
        internal static string check_persistent {
            get {
                return ResourceManager.GetString("check_persistent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enable rMod.
        /// </summary>
        internal static string check_rmod {
            get {
                return ResourceManager.GetString("check_rmod", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Whitelisted.
        /// </summary>
        internal static string check_whitelisted {
            get {
                return ResourceManager.GetString("check_whitelisted", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Codec Quality.
        /// </summary>
        internal static string codecquality {
            get {
                return ResourceManager.GetString("codecquality", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CPU Count.
        /// </summary>
        internal static string cpucount {
            get {
                return ResourceManager.GetString("cpucount", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Database name.
        /// </summary>
        internal static string databasename {
            get {
                return ResourceManager.GetString("databasename", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Difficulty.
        /// </summary>
        internal static string difficulty {
            get {
                return ResourceManager.GetString("difficulty", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string group_about {
            get {
                return ResourceManager.GetString("group_about", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Autobackup.
        /// </summary>
        internal static string group_autobackup {
            get {
                return ResourceManager.GetString("group_autobackup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Backup.
        /// </summary>
        internal static string group_backup {
            get {
                return ResourceManager.GetString("group_backup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to BattlEye.
        /// </summary>
        internal static string group_battleye {
            get {
                return ResourceManager.GetString("group_battleye", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string group_message {
            get {
                return ResourceManager.GetString("group_message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to MySQL.
        /// </summary>
        internal static string group_mysql {
            get {
                return ResourceManager.GetString("group_mysql", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Login information.
        /// </summary>
        internal static string group_mysql_details {
            get {
                return ResourceManager.GetString("group_mysql_details", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string group_other {
            get {
                return ResourceManager.GetString("group_other", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string group_profile {
            get {
                return ResourceManager.GetString("group_profile", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string group_reset {
            get {
                return ResourceManager.GetString("group_reset", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        internal static string group_restore {
            get {
                return ResourceManager.GetString("group_restore", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Scripting.
        /// </summary>
        internal static string group_scripting {
            get {
                return ResourceManager.GetString("group_scripting", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string group_settings {
            get {
                return ResourceManager.GetString("group_settings", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Signatures.
        /// </summary>
        internal static string group_signatures {
            get {
                return ResourceManager.GetString("group_signatures", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Survivor.
        /// </summary>
        internal static string group_survivor {
            get {
                return ResourceManager.GetString("group_survivor", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Mission.
        /// </summary>
        internal static string group_template {
            get {
                return ResourceManager.GetString("group_template", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string group_time {
            get {
                return ResourceManager.GetString("group_time", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Network Tuning.
        /// </summary>
        internal static string group_tuning_network {
            get {
                return ResourceManager.GetString("group_tuning_network", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Performance Tuning.
        /// </summary>
        internal static string group_tuning_performance {
            get {
                return ResourceManager.GetString("group_tuning_performance", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Voice Over Net.
        /// </summary>
        internal static string group_von {
            get {
                return ResourceManager.GetString("group_von", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to GUID.
        /// </summary>
        internal static string guid {
            get {
                return ResourceManager.GetString("guid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Instance.
        /// </summary>
        internal static string instance {
            get {
                return ResourceManager.GetString("instance", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Inventory.
        /// </summary>
        internal static string inventory {
            get {
                return ResourceManager.GetString("inventory", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to kB.
        /// </summary>
        internal static string kilobyte {
            get {
                return ResourceManager.GetString("kilobyte", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Global loadout.
        /// </summary>
        internal static string loadout {
            get {
                return ResourceManager.GetString("loadout", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Global backpack loadout.
        /// </summary>
        internal static string loadoutbackpack {
            get {
                return ResourceManager.GetString("loadoutbackpack", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Max. Bandwidth.
        /// </summary>
        internal static string maxbandwidth {
            get {
                return ResourceManager.GetString("maxbandwidth", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Max. Custom File Size.
        /// </summary>
        internal static string maxcustomsize {
            get {
                return ResourceManager.GetString("maxcustomsize", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Max. Messages Sent.
        /// </summary>
        internal static string maxmsgsent {
            get {
                return ResourceManager.GetString("maxmsgsent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Max. Ping.
        /// </summary>
        internal static string maxping {
            get {
                return ResourceManager.GetString("maxping", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Max. Players.
        /// </summary>
        internal static string maxplayers {
            get {
                return ResourceManager.GetString("maxplayers", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Max. Size Guaranteed.
        /// </summary>
        internal static string maxsizeguaranteed {
            get {
                return ResourceManager.GetString("maxsizeguaranteed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Max. Size Nonguaranteed.
        /// </summary>
        internal static string maxsizenonguaranteed {
            get {
                return ResourceManager.GetString("maxsizenonguaranteed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Max. Vehicle Count.
        /// </summary>
        internal static string maxvehicles {
            get {
                return ResourceManager.GetString("maxvehicles", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Medical.
        /// </summary>
        internal static string medical {
            get {
                return ResourceManager.GetString("medical", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string message {
            get {
                return ResourceManager.GetString("message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to add the following database:.
        /// </summary>
        internal static string message_confirm_database {
            get {
                return ResourceManager.GetString("message_confirm_database", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the log file?.
        /// </summary>
        internal static string message_confirm_deletelog {
            get {
                return ResourceManager.GetString("message_confirm_deletelog", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to add the following player to the whitelist:.
        /// </summary>
        internal static string message_confirm_player {
            get {
                return ResourceManager.GetString("message_confirm_player", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Database creation failed:.
        /// </summary>
        internal static string message_error_database {
            get {
                return ResourceManager.GetString("message_error_database", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Database restore failed:.
        /// </summary>
        internal static string message_error_restore {
            get {
                return ResourceManager.GetString("message_error_restore", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Database was created!.
        /// </summary>
        internal static string message_finished_database {
            get {
                return ResourceManager.GetString("message_finished_database", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Database was cleared!.
        /// </summary>
        internal static string message_finished_reset {
            get {
                return ResourceManager.GetString("message_finished_reset", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Database was restored!.
        /// </summary>
        internal static string message_finished_restore {
            get {
                return ResourceManager.GetString("message_finished_restore", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Do you really want to reset the whole database? All progress is deleted!.
        /// </summary>
        internal static string message_reset {
            get {
                return ResourceManager.GetString("message_reset", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Join Message.
        /// </summary>
        internal static string messagejoin {
            get {
                return ResourceManager.GetString("messagejoin", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Seconds between messages.
        /// </summary>
        internal static string messagetime {
            get {
                return ResourceManager.GetString("messagetime", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Min. Bandwidth.
        /// </summary>
        internal static string minbandwidth {
            get {
                return ResourceManager.GetString("minbandwidth", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Min. Errors to Send.
        /// </summary>
        internal static string minerrtosend {
            get {
                return ResourceManager.GetString("minerrtosend", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Min. Errors to Send Near.
        /// </summary>
        internal static string minerrtosendnear {
            get {
                return ResourceManager.GetString("minerrtosendnear", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Modlist.
        /// </summary>
        internal static string modlist {
            get {
                return ResourceManager.GetString("modlist", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to MySQL Credentials.
        /// </summary>
        internal static string mysql_credentials {
            get {
                return ResourceManager.GetString("mysql_credentials", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to MySQL Host Address.
        /// </summary>
        internal static string mysql_host {
            get {
                return ResourceManager.GetString("mysql_host", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Admin Password.
        /// </summary>
        internal static string passwordadmin {
            get {
                return ResourceManager.GetString("passwordadmin", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to BattlEye Password.
        /// </summary>
        internal static string passwordrcon {
            get {
                return ResourceManager.GetString("passwordrcon", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        internal static string port {
            get {
                return ResourceManager.GetString("port", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        internal static string position {
            get {
                return ResourceManager.GetString("position", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Reporting IP.
        /// </summary>
        internal static string reportingip {
            get {
                return ResourceManager.GetString("reportingip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Require SecureID.
        /// </summary>
        internal static string requiresecureid {
            get {
                return ResourceManager.GetString("requiresecureid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enter the interval in minutes in which a backup should be created:.
        /// </summary>
        internal static string sentence_backupinterval {
            get {
                return ResourceManager.GetString("sentence_backupinterval", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Choose your language:.
        /// </summary>
        internal static string sentence_chooselanguage {
            get {
                return ResourceManager.GetString("sentence_chooselanguage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Options for server name, security switches like a password or the whitelist and which mod to start can be found here..
        /// </summary>
        internal static string sentence_menu1_description {
            get {
                return ResourceManager.GetString("sentence_menu1_description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Start the server, change the mysql connection or view the server log here. The webfrontend allows easy monitoring..
        /// </summary>
        internal static string sentence_menu2_description {
            get {
                return ResourceManager.GetString("sentence_menu2_description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Manage the database with chive. Edit players, add new ones to the whitelist or backup and restore your database here..
        /// </summary>
        internal static string sentence_menu3_description {
            get {
                return ResourceManager.GetString("sentence_menu3_description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Change the display language or get information about this application..
        /// </summary>
        internal static string sentence_menu4_description {
            get {
                return ResourceManager.GetString("sentence_menu4_description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Note: Use this pattern for your text: &quot;Message 1&quot;,&quot;Message 2&quot;,&quot;...&quot;.
        /// </summary>
        internal static string sentence_message {
            get {
                return ResourceManager.GetString("sentence_message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Warning! This deletes the whole database!.
        /// </summary>
        internal static string sentence_reset {
            get {
                return ResourceManager.GetString("sentence_reset", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Server instance to manage:.
        /// </summary>
        internal static string sentence_selectinstance {
            get {
                return ResourceManager.GetString("sentence_selectinstance", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Server name.
        /// </summary>
        internal static string servername {
            get {
                return ResourceManager.GetString("servername", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Basic.
        /// </summary>
        internal static string tab1_page1 {
            get {
                return ResourceManager.GetString("tab1_page1", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        internal static string tab1_page2 {
            get {
                return ResourceManager.GetString("tab1_page2", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        internal static string tab1_page3 {
            get {
                return ResourceManager.GetString("tab1_page3", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Manage.
        /// </summary>
        internal static string tab2_page1 {
            get {
                return ResourceManager.GetString("tab2_page1", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        internal static string tab2_page2 {
            get {
                return ResourceManager.GetString("tab2_page2", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Logs.
        /// </summary>
        internal static string tab2_page3 {
            get {
                return ResourceManager.GetString("tab2_page3", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Manage.
        /// </summary>
        internal static string tab3_page1 {
            get {
                return ResourceManager.GetString("tab3_page1", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Players.
        /// </summary>
        internal static string tab3_page2 {
            get {
                return ResourceManager.GetString("tab3_page2", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Backup.
        /// </summary>
        internal static string tab3_page3 {
            get {
                return ResourceManager.GetString("tab3_page3", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Mission Template.
        /// </summary>
        internal static string template {
            get {
                return ResourceManager.GetString("template", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Timezone.
        /// </summary>
        internal static string timezone {
            get {
                return ResourceManager.GetString("timezone", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to UID.
        /// </summary>
        internal static string uid {
            get {
                return ResourceManager.GetString("uid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Verify Signatures.
        /// </summary>
        internal static string verifysignatures {
            get {
                return ResourceManager.GetString("verifysignatures", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string version {
            get {
                return ResourceManager.GetString("version", resourceCulture);
            }
        }
    }
}
