//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crosire.Controlcenter {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal partial class frmMain {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Crosire.Controlcenter.Crosire.Controlcenter.frmMain", typeof(frmMain).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to [[&quot;Mk_48_DZ&quot;,&quot;NVGoggles&quot;,&quot;Binocular_Vector&quot;,&quot;M9SD&quot;,&quot;ItemGPS&quot;,&quot;ItemToolbox&quot;,&quot;ItemEtool&quot;,&quot;ItemCompass&quot;,&quot;ItemMatchbox&quot;,&quot;FoodCanBakedBeans&quot;,&quot;ItemKnife&quot;,&quot;ItemMap&quot;,&quot;ItemWatch&quot;],[[&quot;100Rnd_762x51_M240&quot;,47],&quot;ItemPainkiller&quot;,&quot;ItemBandage&quot;,&quot;15Rnd_9x19_M9SD&quot;,&quot;100Rnd_762x51_M240&quot;,&quot;ItemBandage&quot;,&quot;ItemBandage&quot;,&quot;15Rnd_9x19_M9SD&quot;,&quot;15Rnd_9x19_M9SD&quot;,&quot;15Rnd_9x19_M9SD&quot;,&quot;ItemMorphine&quot;,&quot;PartWoodPile&quot;]].
        /// </summary>
        internal static string cbxLoadout_Items {
            get {
                return ResourceManager.GetString("cbxLoadout.Items", resourceCulture);
            }
        }
    }
}
